#!/bin/sh
# Regenerates platforms/<system>/region-<r>.xml (r = us, jp, br) for every platform that has
# regional artwork in platforms/<system>/images/<r>/, and removes the stale ones.
#
# Usage (from anywhere):  sh tools/update-regions.sh
#
# Regional artwork (any of these, svg > png > webp):
#   images/<r>/logo.*          logo for that region (system list and game list)
#   images/<r>/logo-w.*        white variant, used on dark palettes (optional)
#   images/<r>/consolegame.*   console picture
#   images/<r>/controller.*    controller picture
#
# theme.xml includes region-<r>.xml only when the "Region" option is set to <r>
# (Theme Configuration -> Region). Whatever a region does not provide falls back
# to the normal artwork of the platform, so a region folder can be partial.
# To add a region image: drop it in the folder above and run this script.

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root/platforms" || exit 1

# pick <path-without-extension>: prints the first existing file (svg, png, webp)
pick() {
    for e in svg png webp; do
        if [ -f "$1.$e" ]; then echo "$1.$e"; return; fi
    done
}

made=0; removed=0
for d in */; do
    p="${d%/}"
    for r in us jp br; do
        xml="$p/region-$r.xml"
        dir="$p/images/$r"
        logo="$(pick "$dir/logo")"
        logow="$(pick "$dir/logo-w")"
        cons="$(pick "$dir/consolegame")"
        ctl="$(pick "$dir/controller")"
        if [ -z "$logo$logow$cons$ctl" ]; then
            if [ -f "$xml" ]; then rm "$xml"; removed=$((removed + 1)); fi
            continue
        fi
        {
            printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
            printf '%s\n' "<!-- Regional artwork (images/$r/). Generated by tools/update-regions.sh. -->"
            printf '%s\n' '<theme>'
            if [ -n "$logo$cons$ctl" ]; then
                printf '%s\n' '    <variables>'
                if [ -n "$logo" ]; then
                    printf '        <systemLogo>./platforms/%s/images/%s/%s</systemLogo>\n' "$p" "$r" "${logo##*/}"
                    printf '        <gamelistLogo>./platforms/%s/images/%s/%s</gamelistLogo>\n' "$p" "$r" "${logo##*/}"
                fi
                if [ -n "$cons" ]; then
                    printf '        <systemConsoleImage>./platforms/%s/images/%s/%s</systemConsoleImage>\n' "$p" "$r" "${cons##*/}"
                fi
                if [ -n "$ctl" ]; then
                    printf '        <systemControllerImage>./platforms/%s/images/%s/%s</systemControllerImage>\n' "$p" "$r" "${ctl##*/}"
                fi
                printf '%s\n' '    </variables>'
            fi
            if [ -n "$logow" ]; then
                printf '%s\n' '    <variables if="${logoVariantSystem} == '"'white'"'">'
                printf '        <systemLogo>./platforms/%s/images/%s/%s</systemLogo>\n' "$p" "$r" "${logow##*/}"
                printf '%s\n' '    </variables>'
                printf '%s\n' '    <variables if="${logoVariantGamelist} == '"'white'"'">'
                printf '        <gamelistLogo>./platforms/%s/images/%s/%s</gamelistLogo>\n' "$p" "$r" "${logow##*/}"
                printf '%s\n' '    </variables>'
            fi
            printf '%s\n' '</theme>'
        } > "$xml"
        made=$((made + 1))
    done
done
echo "region-*.xml: $made generated, $removed removed"
