#!/bin/sh
# Regenerates platforms/<system>/logo-w.xml for every platform that has
# images/logo-w.svg, and removes the stale ones whose logo-w.svg is gone.
#
# Usage (from anywhere):  sh tools/update-dark-logos.sh
#
# Workflow to add a white logo for a platform:
#   1. drop the file as platforms/<system>/images/logo-w.svg
#   2. run this script
# Without logo-w.svg the platform keeps using images/logo.svg on dark palettes.

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root/platforms" || exit 1

made=0; removed=0
for d in */; do
    p="${d%/}"
    xml="$p/logo-w.xml"
    if [ -f "$p/images/logo-w.svg" ]; then
        cat > "$xml" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- Dark-palette logo variant (images/logo-w.svg). Generated by tools/update-dark-logos.sh. -->
<theme>
    <variables if="\${logoVariantSystem} == 'white'">
        <systemLogo>./platforms/$p/images/logo-w.svg</systemLogo>
    </variables>
    <variables if="\${logoVariantGamelist} == 'white'">
        <gamelistLogo>./platforms/$p/images/logo-w.svg</gamelistLogo>
    </variables>
</theme>
XML
        made=$((made + 1))
    elif [ -f "$xml" ]; then
        rm "$xml"
        removed=$((removed + 1))
    fi
done
echo "logo-w.xml: $made generated, $removed removed"
